// Cleveland Way – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["cleveland-way"] = {
  name: "Cleveland Way",
  route: "Helmsley to Filey Brigg",
  startLabel: "Helmsley",
  endLabel: "Filey Brigg",
  colour: "#5b3a6b",
  subtitle: "Helmsley, North Yorkshire, over the moors then down the coast to Filey Brigg",
  footer: "Section distances from the official National Trail route pages (nationaltrail.co.uk). The official 109-mile figure includes short detours; the sections add up to 106.6 miles. Section-end towns use the official figures; intermediate landmarks are estimated positions between them (&plusmn;0.5 mile). GPS distances on the ground will read a little longer.",
  landmarks: [
    ["Helmsley", 0],
    ["Rievaulx Abbey", 2.5],
    ["Cold Kirby", 7],
    ["Sutton Bank", 10, "visitor centre; Moorsbus / taxi"],
    ["Whitestone Cliff", 11.5],
    ["Sneck Yate", 14],
    ["High Paradise", 16],
    ["Square Corner (Oakdale)", 19],
    ["Osmotherley", 21.5, "buses to Northallerton"],
    ["Scarth Nick", 23.5],
    ["Lord Stones", 28.5],
    ["Wainstones", 31],
    ["Clay Bank", 32.5, "B1257; taxi"],
    ["Urra Moor (Round Hill)", 35],
    ["Bloworth Crossing", 37],
    ["Kildale", 41.8, "station"],
    ["Captain Cook's Monument", 43.5],
    ["Roseberry Topping", 46.5],
    ["Highcliffe Nab", 49.5],
    ["Slapewath", 51.5],
    ["Skelton", 53.5],
    ["Saltburn", 56.6, "station"],
    ["Skinningrove", 60.5],
    ["Boulby Cliff", 63],
    ["Staithes", 65.5],
    ["Runswick Bay", 69.5, "buses"],
    ["Kettleness", 71.5],
    ["Sandsend", 74.1],
    ["Whitby", 77.1, "station"],
    ["Saltwick Bay", 78.6],
    ["Robin Hood's Bay", 84.1, "buses"],
    ["Ravenscar", 87.6],
    ["Hayburn Wyke", 90.6],
    ["Cloughton Wyke", 92.1],
    ["Scarborough", 96.1, "station"],
    ["Cayton Bay", 100.1],
    ["Filey", 105.1, "station"],
    ["Filey Brigg", 106.6, "finish"],
  ],
  stages: [
    { from: "Helmsley", to: "Sutton Bank", note: "Steady climb past Rievaulx" },
    { from: "Sutton Bank", to: "Osmotherley" },
    { from: "Osmotherley", to: "Clay Bank", note: "Very hilly: five moor-edge climbs" },
    { from: "Clay Bank", to: "Kildale", note: "Short; highest point on Urra Moor" },
    { from: "Kildale", to: "Saltburn", note: "Roseberry Topping is an optional extra" },
    { from: "Saltburn", to: "Runswick Bay", note: "Cliff-top, some steep drops to Staithes" },
    { from: "Runswick Bay", to: "Robin Hood's Bay", note: "Whitby at 7.6 mi (station)" },
    { from: "Robin Hood's Bay", to: "Scarborough" },
    { from: "Scarborough", to: "Filey Brigg", note: "Gentle finish" },
  ],
};
