// Cotswold Way – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["cotswold-way"] = {
  name: "Cotswold Way",
  route: "Chipping Campden to Bath",
  startLabel: "Chipping Campden",
  endLabel: "Bath",
  colour: "#8a6d1d",
  subtitle: "Chipping Campden, Gloucestershire along the Cotswold escarpment to Bath Abbey",
  footer: "Section distances from the official National Trail route pages (nationaltrail.co.uk). The escarpment means lots of short, steep climbs even though the hills are not high. Section-end towns use the official figures; intermediate landmarks are estimated positions between them (&plusmn;0.5 mile). GPS distances on the ground will read a little longer.",
  landmarks: [
    ["Chipping Campden", 0, "buses"],
    ["Dover's Hill", 1],
    ["Broadway Tower", 5],
    ["Broadway", 6, "buses"],
    ["Stanton", 9.5],
    ["Wood Stanway", 12.5, "taxi/Uber"],
    ["Hailes Abbey", 15.5],
    ["Winchcombe", 17.9, "buses"],
    ["Belas Knap", 20],
    ["Cleeve Hill", 23.5, "buses to Cheltenham"],
    ["Cleeve Common summit", 25],
    ["Dowdeswell", 29],
    ["Seven Springs", 31],
    ["Leckhampton Hill", 33.7],
    ["Crickley Hill Country Park", 36.5, "taxi/Uber"],
    ["Birdlip", 39.3],
    ["Cooper's Hill", 42],
    ["Painswick Beacon", 45.5],
    ["Painswick", 47.9, "buses"],
    ["Haresfield Beacon", 51.5],
    ["King's Stanley", 55.7, "buses"],
    ["Coaley Peak", 58.5, "picnic site; taxi/Uber"],
    ["Dursley", 62.9, "buses"],
    ["Stinchcombe Hill", 64.5],
    ["Tyndale Monument", 67.5],
    ["Wotton-under-Edge", 70.2, "buses"],
    ["Hawkesbury Upton", 77.6],
    ["Horton", 80],
    ["Old Sodbury", 83, "pub; buses"],
    ["Tormarton", 85.3],
    ["Dyrham", 88.5],
    ["Cold Ashton", 91.9, "taxi/Uber"],
    ["Lansdown", 96],
    ["Weston", 99.5],
    ["Bath Abbey", 102.1, "finish; station"],
  ],
  stages: [
    { from: "Chipping Campden", to: "Wood Stanway", note: "Broadway at 6 mi (buses)" },
    { from: "Wood Stanway", to: "Cleeve Hill", note: "Winchcombe at 5.4 mi" },
    { from: "Cleeve Hill", to: "Crickley Hill Country Park", note: "Highest point on Cleeve Common" },
    { from: "Crickley Hill Country Park", to: "Painswick", note: "Steep Cooper's Hill" },
    { from: "Painswick", to: "Coaley Peak", note: "Haresfield Beacon; King's Stanley (buses) at 7.8 mi" },
    { from: "Coaley Peak", to: "Wotton-under-Edge", note: "Cam Long Down, Dursley (buses) at 4.4 mi, Stinchcombe Hill" },
    { from: "Wotton-under-Edge", to: "Old Sodbury" },
    { from: "Old Sodbury", to: "Cold Ashton" },
    { from: "Cold Ashton", to: "Bath Abbey" },
  ],
};
