// Glyndŵr's Way – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["glyndwrs-way"] = {
  name: "Glyndŵr's Way",
  route: "Knighton to Welshpool",
  startLabel: "Knighton",
  endLabel: "Welshpool",
  colour: "#6b2a2a",
  subtitle: "Knighton through the hills of mid-Wales via Machynlleth to Welshpool",
  footer: "Section distances from the official National Trail route pages (nationaltrail.co.uk). This is remote country: few buses, so most stage ends need a pre-booked taxi. Section-end towns use the official figures; intermediate landmarks are estimated positions between them (&plusmn;0.5 mile). GPS distances on the ground will read a little longer.",
  landmarks: [
    ["Knighton", 0, "station"],
    ["Llangunllo", 6, "station"],
    ["Beacon Hill", 11],
    ["Felindre", 15, "taxi"],
    ["Llanbadarn Fynydd", 22],
    ["Castell y Blaidd", 25],
    ["Abbeycwmhir", 30.5, "taxi"],
    ["Bwlch-y-sarnau", 34],
    ["Llanidloes", 46, "buses"],
    ["Clywedog Dam", 50],
    ["Staylittle", 57],
    ["Dylife", 60.5, "taxi"],
    ["Glaslyn", 64],
    ["Foel Fadian", 65],
    ["Machynlleth", 75, "station"],
    ["Abercegir", 82],
    ["Commins Coch", 86],
    ["Llanbrynmair", 91, "buses"],
    ["Llangadfan", 100, "taxi"],
    ["Llanwddyn (Lake Vyrnwy)", 109],
    ["Dolanog", 114, "taxi"],
    ["Pontrobert", 118],
    ["Meifod", 124, "buses"],
    ["Y Golfa", 131],
    ["Welshpool", 135, "finish; station"],
  ],
  stages: [
    { from: "Knighton", to: "Felindre", note: "Beacon Hill moorland" },
    { from: "Felindre", to: "Abbeycwmhir", note: "Remote moorland" },
    { from: "Abbeycwmhir", to: "Llanidloes" },
    { from: "Llanidloes", to: "Dylife", note: "Clywedog reservoir" },
    { from: "Dylife", to: "Machynlleth", note: "High moorland; Glaslyn" },
    { from: "Machynlleth", to: "Llanbrynmair", note: "Ridge walking" },
    { from: "Llanbrynmair", to: "Llangadfan", note: "Short; forestry" },
    { from: "Llangadfan", to: "Dolanog", note: "Via Lake Vyrnwy" },
    { from: "Dolanog", to: "Meifod", note: "Riverside, gentle" },
    { from: "Meifod", to: "Welshpool", note: "Y Golfa climb near the end" },
  ],
};
