// Pennine Way – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["pennine-way"] = {
  name: "Pennine Way",
  route: "Edale to Kirk Yetholm",
  startLabel: "Edale",
  endLabel: "Kirk Yetholm",
  colour: "#3d4f2a",
  subtitle: "Edale, Derbyshire along the Pennine spine to Kirk Yetholm in the Scottish Borders",
  footer: "Day-stage distances from the official National Trail route pages (nationaltrail.co.uk), which add up to 254.5 miles. The official 268-mile figure includes spurs such as The Cheviot. A serious upland walk: carry navigation and bad-weather kit, especially on Cross Fell and the Cheviots. Section-end towns use the official figures; intermediate landmarks are estimated positions between them (&plusmn;0.5 mile). GPS distances on the ground will read a little longer.",
  landmarks: [
    ["Edale", 0, "station"],
    ["Jacob's Ladder", 3.5],
    ["Kinder Downfall", 6],
    ["Mill Hill", 8],
    ["Snake Pass (A57)", 10, "taxi/Uber"],
    ["Bleaklow Head", 12.5],
    ["Crowden", 16],
    ["Black Hill", 20.5],
    ["Wessenden Head (A635)", 22.5, "taxi; Marsden 3 mi"],
    ["Standedge", 27, "buses"],
    ["Blackstone Edge", 31.5],
    ["Stoodley Pike", 35.5],
    ["Calder Valley (Hebden Bridge)", 38, "station"],
    ["Walshaw Dean", 42],
    ["Top Withins", 45],
    ["Ponden", 47],
    ["Ickornshaw (Cowling)", 54, "buses"],
    ["Lothersdale", 57],
    ["Thornton-in-Craven", 61],
    ["Gargrave", 65, "station"],
    ["Airton", 68],
    ["Malham", 71, "buses"],
    ["Malham Tarn", 73.5],
    ["Fountains Fell", 77],
    ["Pen-y-ghent", 81.5],
    ["Horton in Ribblesdale", 85.5, "station"],
    ["Cam End", 91],
    ["Dodd Fell", 95],
    ["Hawes", 99.5, "buses"],
    ["Great Shunner Fell", 105.5],
    ["Thwaite", 108.5],
    ["Keld", 111.5, "taxi"],
    ["Tan Hill Inn", 116],
    ["God's Bridge", 122.5],
    ["Baldersdale", 126.5, "taxi"],
    ["Middleton-in-Teesdale", 133, "buses"],
    ["High Force", 138],
    ["Langdon Beck", 141.5, "hotel/YHA; taxi"],
    ["Cauldron Snout", 145],
    ["High Cup Nick", 150],
    ["Dufton", 154, "taxi"],
    ["Great Dun Fell", 159.5],
    ["Cross Fell", 162],
    ["Garrigill", 169, "taxi"],
    ["Alston", 174, "buses"],
    ["Slaggyford", 179.5],
    ["Knarsdale", 182, "pub; taxi"],
    ["Greenhead", 190.5, "buses"],
    ["Steel Rigg (Once Brewed)", 196.5, "AD122 bus"],
    ["Warks Burn", 205],
    ["Bellingham", 212.5, "buses"],
    ["Padon Hill", 218.5],
    ["Byrness", 227.5, "buses"],
    ["Chew Green", 233.5],
    ["Windy Gyle", 241.5, "descend to Barrowburn; taxi"],
    ["Auchope Cairn", 247.5],
    ["Kirk Yetholm", 254.5, "finish; buses"],
  ],
  stages: [
    { from: "Edale", to: "Snake Pass (A57)", note: "Kinder plateau; short but tough" },
    { from: "Snake Pass (A57)", to: "Wessenden Head (A635)", note: "Bleaklow and Black Hill: peat, navigation" },
    { from: "Wessenden Head (A635)", to: "Calder Valley (Hebden Bridge)", note: "Moorland edges" },
    { from: "Calder Valley (Hebden Bridge)", to: "Ickornshaw (Cowling)", note: "Bail-out at Ponden (9 mi)" },
    { from: "Ickornshaw (Cowling)", to: "Malham", note: "Longest but gentle lowland; Gargrave station at 11 mi" },
    { from: "Malham", to: "Horton in Ribblesdale", note: "Fountains Fell and Pen-y-ghent" },
    { from: "Horton in Ribblesdale", to: "Hawes", note: "Long, steady moor tracks" },
    { from: "Hawes", to: "Keld", note: "Great Shunner Fell" },
    { from: "Keld", to: "Baldersdale", note: "Tan Hill, boggy Sleightholme Moor" },
    { from: "Baldersdale", to: "Langdon Beck", note: "Middleton at 6.5 mi; riverside Tees" },
    { from: "Langdon Beck", to: "Dufton", note: "Cauldron Snout scramble, High Cup" },
    { from: "Dufton", to: "Garrigill", note: "Toughest: Cross Fell, highest point" },
    { from: "Garrigill", to: "Knarsdale", note: "South Tyne valley" },
    { from: "Knarsdale", to: "Steel Rigg (Once Brewed)", note: "Onto Hadrian's Wall crags" },
    { from: "Steel Rigg (Once Brewed)", to: "Bellingham", note: "Wark Forest" },
    { from: "Bellingham", to: "Byrness", note: "Moor and forest" },
    { from: "Byrness", to: "Windy Gyle", note: "Cheviot ridge; +1.5 mi descent" },
    { from: "Windy Gyle", to: "Kirk Yetholm", note: "Cheviot ridge to the finish" },
  ],
};
