// The Ridgeway – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["ridgeway"] = {
  name: "The Ridgeway",
  route: "Overton Hill to Ivinghoe Beacon",
  startLabel: "Overton Hill",
  endLabel: "Ivinghoe Beacon",
  colour: "#6a5a2a",
  subtitle: "Overton Hill near Avebury along the chalk downs and Chilterns to Ivinghoe Beacon",
  footer: "Section distances from the official National Trail route pages (nationaltrail.co.uk). The western half is remote and exposed, with few taps. The Chilterns stretch from Watlington to Wendover is the most up-and-down. Section-end towns use the official figures; intermediate landmarks are estimated positions between them (&plusmn;0.5 mile). GPS distances on the ground will read a little longer.",
  landmarks: [
    ["Overton Hill (near Avebury)", 0, "taxi"],
    ["Hackpen Hill", 4.5],
    ["Barbury Castle", 7],
    ["Ogbourne St George", 9.3],
    ["Liddington Hill", 14, "buses from Chiseldon"],
    ["Foxhill (M4)", 16.5],
    ["Wayland's Smithy", 22.5],
    ["Uffington White Horse", 24],
    ["Sparsholt Firs", 25.3, "taxi to Wantage"],
    ["Segsbury Camp", 29.5],
    ["A34 underpass", 35],
    ["Bury Down", 37, "taxi"],
    ["Streatley", 42.7, "Goring station"],
    ["South Stoke", 45.5],
    ["North Stoke", 47.5],
    ["Grim's Ditch", 49],
    ["Nuffield", 52, "taxi/Uber"],
    ["Swyncombe", 54],
    ["Watlington", 58, "buses"],
    ["Chinnor", 64.5, "buses"],
    ["Princes Risborough", 69.5, "station"],
    ["Whiteleaf", 70.5],
    ["Wendover", 75, "station"],
    ["Hastoe", 80],
    ["Tring station", 82, "station"],
    ["Pitstone Hill", 83.5],
    ["Ivinghoe Beacon", 86.8, "finish; taxi"],
  ],
  stages: [
    { from: "Overton Hill (near Avebury)", to: "Liddington Hill", note: "Barbury Castle" },
    { from: "Liddington Hill", to: "Sparsholt Firs", note: "Remote; Uffington White Horse" },
    { from: "Sparsholt Firs", to: "Bury Down", note: "Open downland gallops" },
    { from: "Bury Down", to: "Nuffield", note: "Thames at Streatley (5.7 mi)" },
    { from: "Nuffield", to: "Chinnor", note: "Watlington at 6 mi" },
    { from: "Chinnor", to: "Wendover", note: "Undulating Chiltern woods" },
    { from: "Wendover", to: "Ivinghoe Beacon", note: "Final climb to the Beacon" },
  ],
};
