// Thames Path – landmarks are [name, miles from start, optional note].
// To record a finished stage, add  date: "d Mon yyyy", steps: 12345  to it in the stages list.
window.TRAILS = window.TRAILS || {};
window.TRAILS["thames-path"] = {
  name: "Thames Path",
  route: "Sea to Source",
  startLabel: "Woolwich",
  endLabel: "Source",
  colour: "#1b4f72",
  subtitle: "Woolwich Ferry to the Source near Kemble, Gloucestershire",
  footer: "Distances sourced from walkthethames.co.uk (Ordnance Survey 1:25,000). GPS distances on the ground will be slightly longer, especially through London where the path has more twists and turns. Stages 3 and 5 now start where the previous stage ended (Kingston and Eton &amp; Windsor), so all 183.1 miles are counted.",
  landmarks: [
    ["Woolwich Ferry", 0.0],
    ["Thames Barrier", 1.2],
    ["North Greenwich", 2.8],
    ["Greenwich", 5.3],
    ["Canary Wharf Pier", 7.7],
    ["Rotherhithe & Wapping", 9.4],
    ["Tower Bridge", 10.5],
    ["London Bridge", 11.2],
    ["Southwark Bridge", 11.5],
    ["Blackfriars Bridge", 11.9],
    ["Waterloo Bridge", 12.5],
    ["Westminster Bridge", 13.0],
    ["Lambeth Bridge", 13.4],
    ["Vauxhall Bridge", 14.1],
    ["Chelsea Bridge", 15.6],
    ["Albert Bridge", 16.4],
    ["Battersea Bridge", 16.6],
    ["Wandsworth Bridge", 18.1],
    ["Putney Bridge (cross to north)", 19.7],
    ["Hammersmith Bridge (cross to south)", 21.4],
    ["Barnes Bridge", 23.2],
    ["Kew Bridge", 25.3],
    ["Richmond Lock & Isleworth", 27.2],
    ["Richmond", 28.3],
    ["Ham House Ferry / Twickenham", 29.3],
    ["Teddington Lock", 31.1],
    ["Kingston upon Thames", 32.7],
    ["Hampton Court", 35.6],
    ["Sunbury Lock", 38.7],
    ["Walton-on-Thames", 40.4],
    ["Shepperton Ferry (cross to north)", 41.8],
    ["Chertsey Bridge", 43.7],
    ["Laleham", 45.2],
    ["Staines", 47.6],
    ["Runnymede", 50.3],
    ["Bells of Ouzeley", 50.7],
    ["Albert Bridge, Old Windsor", 52.5],
    ["Datchet", 54.2],
    ["Eton & Windsor", 55.6],
    ["Dorney Lake", 57.9],
    ["Dorney / Bray Marina", 59.7],
    ["Maidenhead", 62.2],
    ["Cookham", 65.4],
    ["Bourne End", 66.8],
    ["Marlow", 69.8],
    ["Hurley", 72.1],
    ["Aston", 75.2],
    ["Hambleden Lock", 76.5],
    ["Remenham", 77.1],
    ["Henley-on-Thames", 78.3],
    ["Shiplake", 82.0],
    ["Shiplake College Boathouse", 84.3],
    ["Sonning", 86.4],
    ["Kennet Canal / Reading", 88.6],
    ["Reading Bridge", 89.5],
    ["Tilehurst", 92.8],
    ["Purley on Thames", 93.7],
    ["Whitchurch & Pangbourne", 96.3],
    ["Goring & Streatley", 100.7],
    ["Moulsford", 102.9],
    ["Cholsey", 104.7],
    ["Wallingford", 107.4],
    ["Benson", 109.2],
    ["Shillingford", 110.2],
    ["Dorchester", 112.1],
    ["Days Lock / Little Wittenham", 112.8],
    ["Clifton Hampden", 115.2],
    ["Culham Lock", 118.4],
    ["Culham Old Bridge", 119.7],
    ["Abingdon", 120.6],
    ["Radley Boat House", 124.3],
    ["Sandford Lock", 126.0],
    ["Iffley Lock", 127.7],
    ["Donnington Bridge", 128.1],
    ["Folly Bridge, Oxford", 129.1],
    ["Osney Bridge, Oxford", 130.2],
    ["Godstow Bridge", 132.6],
    ["Swinford Bridge", 136.2],
    ["Pinkhill Lock", 137.2],
    ["Bablock Hythe", 140.0],
    ["Northmoor Lock", 141.5],
    ["Newbridge", 143.7],
    ["Shifford Lock", 146.4],
    ["Tadpole Bridge", 149.7],
    ["Radcot Bridge", 153.7],
    ["Kelmscott", 156.4],
    ["Buscot", 158.2],
    ["Lechlade", 160.1],
    ["Hannington Bridge", 164.5],
    ["Castle Eaton", 166.6],
    ["Cricklade", 170.9],
    ["Water Hay Car Park", 175.0],
    ["Ashton Keynes", 176.3],
    ["Somerford Keynes", 178.8],
    ["Source of the Thames", 183.1],
  ],
  stages: [
    { from: "Woolwich Ferry", to: "Wandsworth Bridge", date: "17 Jun 2026", steps: 41131 },
    { from: "Wandsworth Bridge", to: "Kingston upon Thames", date: "1 Jul 2026", steps: 35676 },
    { from: "Kingston upon Thames", to: "Staines", date: "9 Jul 2026", steps: 28793 },
    { from: "Staines", to: "Eton & Windsor", date: "13 Jul 2026", steps: 23150 },
    { from: "Eton & Windsor", to: "Marlow", date: "15 Jul 2026", steps: 28628 },
    { from: "Marlow", to: "Henley-on-Thames", date: "17 Aug 2026", steps: 21164 },
    { from: "Henley-on-Thames", to: "Tilehurst", date: "1 Sep 2026", steps: 31021 },
    { from: "Tilehurst", to: "Clifton Hampden", date: "8 Sep 2026", steps: 48392 },
    { from: "Clifton Hampden", to: "Osney Bridge, Oxford", date: "9 Sep 2026", steps: 31380 },
    { from: "Osney Bridge, Oxford", to: "Tadpole Bridge", date: "17 Sep 2026", steps: 40185 },
    { from: "Tadpole Bridge", to: "Castle Eaton", date: "18 Sep 2026", steps: 37064 },
    { from: "Castle Eaton", to: "Source of the Thames" },
  ],
};
